repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/astral‑sh/ruff
    rev: v0.4.5
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/pre‑commit/mirrors‑isort
    rev: v5.13.2
    hooks:
      - id: isort
        args: ["--profile=black"]

  - repo: https://github.com/pre‑commit/pre‑commit‑hooks
    rev: v4.6.0
    hooks:
      - id: end‑of‑file‑fix
      - id: check‑yaml
      - id: check‑added‑large‑files

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        stages: [commit]